//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPersonaDao
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Factura
    {
        public int Id { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> Valor { get; set; }
        [DataType("datetime-local")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
